'use strict';

// A room that does not take turns the same way twice.
//
// The three ways a session can ask its agents each have a shape, and the shape
// is the problem. A relay is always a lap in list order. A dialogue is always a
// rota. Watched once they are interesting; watched all afternoon they are a
// machine, and the tell is that you can predict who speaks next before it
// happens.
//
// People are not like that. A real conversation moves between somebody going
// round the room, two people picking at each other's reasoning, and somebody who
// has been quiet saying the thing everybody missed — in no fixed order, and in a
// different order tomorrow.
//
// So Human Like is not a fourth way of asking. It is the three that already
// exist, run one after another in an order rolled fresh for every question:
//
//   In turn            — each agent answers, seeing what has been said
//   Between themselves — each agent replies to the discussion
//   Observer           — whoever has been watching says something, or does not
//
// ---- the two rules that keep it from becoming noise ----
//
// **One turn per agent per segment.** Not a budget, not a cap that usually is
// not reached — exactly one. Three agents is three turns in the relay segment
// and three in the discussion segment, and then that segment is over whatever
// anybody still has to say. A dialogue that loops is the right thing when
// somebody chose a dialogue and set a budget for it; here it would be three
// agents producing a wall of text off one question, which is precisely the
// "spamming like message" this mode exists to avoid.
//
// **One cycle per question.** The arrangement is rolled when the question is
// asked and the round ends when the third segment does. Longer conversations get
// their variety from having more questions in them, not from one question going
// on for ever — and because every question rolls again, two questions in a row
// never run the same shape.
//
// Nothing here talks to an agent or reads a clock. The roll takes its randomness
// as an argument, which is the only reason "never the same twice in a row" is a
// thing a test can prove rather than a thing the code hopes for.

// The three parts, named once. These are the strings a round carries and the
// window renders, so they live here rather than being spelt out at each site.
const IN_TURN = 'relay';
const BETWEEN = 'dialogue';
const OBSERVE = 'observer';

// The six orders those three can come in, numbered as they were specified.
//
// Written out rather than generated by permuting a list of three. There are
// exactly six, they are never going to become twenty-four, and a literal table
// is something a person can read against the specification line by line — which
// is what somebody will actually want to do when a conversation feels wrong.
const ARRANGEMENTS = [
  { n: 1, order: [IN_TURN, BETWEEN, OBSERVE] },
  { n: 2, order: [BETWEEN, IN_TURN, OBSERVE] },
  { n: 3, order: [OBSERVE, BETWEEN, IN_TURN] },
  { n: 4, order: [IN_TURN, OBSERVE, BETWEEN] },
  { n: 5, order: [BETWEEN, OBSERVE, IN_TURN] },
  { n: 6, order: [OBSERVE, IN_TURN, BETWEEN] },
];

// What each part is called where somebody can see it. Plain description rather
// than the mode's own name: "Between themselves" is what the picker calls a
// whole mode, and reusing it for one third of a cycle would suggest the session
// had changed mode mid-question.
const SEGMENT_LABEL = {
  [IN_TURN]: 'each in turn',
  [BETWEEN]: 'between themselves',
  [OBSERVE]: 'whoever has been watching',
};

function arrangement(n) {
  return ARRANGEMENTS.find((a) => a.n === n) || null;
}

// Which shuffle this question runs.
//
// Uniform over the five that are not the last one, so no two questions in a row
// have the same shape — which is the whole of what makes the mode feel unforced.
// Excluding the last is done by removing it from the list rather than by rolling
// again until it differs: a retry loop has no upper bound on how long it takes,
// and this has to be one operation with one answer.
//
// `rand` is an argument so the caller can hand in something deterministic. A
// function that reaches for Math.random cannot be tested for the one property
// that matters about it.
function rollArrangement(last = null, rand = Math.random) {
  const pool = ARRANGEMENTS.filter((a) => a.n !== last);
  // Nothing to avoid, or a `last` that is not one of ours: the whole table is
  // the pool, which is also what the first question in a session gets.
  const from = pool.length ? pool : ARRANGEMENTS;
  const roll = rand();
  // Guard the index rather than trusting the source. A `rand` that returns 1, or
  // something not a number at all, must not index off the end and hand back
  // undefined — this function returning nothing would end a round before it
  // started.
  const at = Number.isFinite(roll)
    ? Math.min(from.length - 1, Math.max(0, Math.floor(roll * from.length)))
    : 0;
  return from[at];
}

// The cycle a question will run, as a list of segments with their speakers
// already decided.
//
// Every agent appears exactly once in every segment they can speak in, and the
// list is built here rather than being worked out as the round goes: a queue
// that is decided in advance is a queue a test can count, and the "one turn
// each" rule becomes a property of the plan rather than a promise about the
// loop that consumes it.
//
// The observer segment gets its own copy of the roster because whether anybody
// speaks in it is not known yet — it is decided by what they have to say, which
// is the point of an observer. Its queue is who *may* speak, and nought of them
// speaking is an ordinary outcome rather than a failure.
function planCycle(chosen, targets) {
  const picked = arrangement(chosen && chosen.n ? chosen.n : chosen) || ARRANGEMENTS[0];
  const roster = (targets || []).slice();
  return {
    arrangement: picked.n,
    segments: picked.order.map((kind) => ({
      kind,
      // How many were due to speak in this segment when it was planned.
      //
      // Kept rather than read off `queue.length`, which shrinks as the segment
      // runs — an agent told "turn 2 of 1" because the queue had already been
      // drained would be told something untrue, and the discussion segment says
      // exactly that to every speaker.
      size: (targets || []).length,
      // A fresh array per segment. Sharing one would let the relay segment's
      // shift() empty the discussion segment's queue, which is the sort of bug
      // that only shows up with three agents and looks like a transport fault.
      queue: roster.slice(),
      // Nobody has spoken in it yet. Counted rather than derived from the queue,
      // because an agent that left the room is removed from the queue and the
      // count of who actually spoke still has to be right.
      spoken: [],
    })),
  };
}

// Whoever is next in this segment, skipping anybody who has left the room.
//
// `gone` is the round's `left` set — agents that signed off, went quiet or could
// not answer. They are dropped here rather than being asked and failing again:
// an agent that could not answer the relay segment is not going to answer the
// discussion segment, and asking it twice would spend a peer's fair share on a
// question already known to be unanswerable.
//
// Returns null when the segment is done, which is the caller's cue to move on.
function nextInSegment(segment, gone) {
  if (!segment) return null;
  const left = gone || new Set();
  while (segment.queue.length) {
    const next = segment.queue.shift();
    if (next && !left.has(next.agentId)) return next;
  }
  return null;
}

// How many turns a whole cycle can possibly cost.
//
// The relay and discussion segments are one each per agent; the observer segment
// is at most one in total, because an observer that spoke would be a second
// unsolicited voice in a room that has just heard everybody twice. Used for the
// "turn N of M" the window shows, so the number somebody watches climb is the
// real ceiling rather than a guess.
function cycleCost(count) {
  const agents = Math.max(0, Number(count) || 0);
  return agents * 2 + 1;
}

// What the window says about where a cycle has got to.
//
// The arrangement number is in it deliberately. It is the only visible sign that
// the order was rolled rather than chosen, and somebody watching two questions
// run differently should be able to see that is what happened rather than
// wondering whether the app is unwell.
function segmentNotice(segment, { index = 0, of = 3, arrangement: n = null } = {}) {
  if (!segment) return null;
  const what = SEGMENT_LABEL[segment.kind];
  if (!what) return null;
  const which = n ? ` · order ${n}` : '';
  return `Part ${index + 1} of ${of}: ${what}${which}`;
}

// Why a Human Like round stopped, when it stopped by finishing.
//
// Its own reason rather than one of dialogue.js's endings: `spent` means a
// budget ran out and `converged` means the agents had nothing further, and this
// is neither. The cycle simply had three parts and did all three.
const CYCLED = 'cycled';

function cycleNotice(arrangementN, { spoke = 0 } = {}) {
  const which = arrangementN ? ` (order ${arrangementN})` : '';
  if (!spoke) return `The round finished${which}.`;
  return `Everyone had their turn${which}. ${spoke} ${spoke === 1 ? 'reply' : 'replies'}.`;
}

module.exports = {
  IN_TURN,
  BETWEEN,
  OBSERVE,
  ARRANGEMENTS,
  SEGMENT_LABEL,
  CYCLED,
  arrangement,
  rollArrangement,
  planCycle,
  nextInSegment,
  cycleCost,
  segmentNotice,
  cycleNotice,
};
